### ISSUE TITLE
Recreating archived keys

### ISSUE THREAD

**Issue by tal952** [Soluto/tweek#1000]
The senerio:
1. create key: my_app/foo
2. archive key: my_app/foo
3. create key: my_app/foo

Step 3 suppose to be disallowed.

**Comment by Yshayy** [comment]
Archived keys stay active, the case for using is them is for keys that are requested by old clients but they are not need to be managed anymore (read-only, hidden).
You can delete archived keys (they are still available in search) which will allow you to create keys with the same name, or alternatively use the un-archive button to restore the key to editable state.
Might worth adding some documentation on this

**Comment by Yshayy** [comment]
Can the key saved afterwards? or is there an error?

**Comment by tal952** [comment]
It can be saved afterwards.
Why the issue is closed?..
