### ISSUE TITLE
UI for changing policies (Gateway)

### ISSUE THREAD

**Issue by Gabrn** [Soluto/tweek#1008]
Are there any design directions for it?
Started working on something and wanted to be in sync with the team in hopes of merging it.

If there aren't any directions currently, maybe we can discuss it here :)

I thought of 2 designs:
1. A 4th page named security, where all the policies will be presented and editable. Somewhat similar to firebase database rules.
2. Add a button for patching policies for a specific key path next to the "+" button in the keys page (this is only relevant to keys though).

I think the combination of both should be enough.

Any other ideas?

**Comment by Gabrn** [comment]
Initial version (It's just an editable json):
![screen shot 2018-12-04 at 17 41 17](https://user-images.githubusercontent.com/10612685/49453482-e370dd00-f7eb-11e8-8002-91cdebe635c3.png)

**Comment by Yshayy** [comment]
Maybe use JSON tabular UI? It kinda has fixed structure and columns

**Comment by Gabrn** [comment]
Sure I can give it a try

**Comment by Yshayy** [comment]
I think we can start with the single page and afterwards create the patch experience as it's a bit more difficult

**Comment by Gabrn** [comment]
Yeah Im working on a more table like design foe the page.
We will add a single patch for keys later on

**Comment by Gabrn** [comment]
What about this?

![screen shot 2018-12-11 at 17 17 21](https://user-images.githubusercontent.com/10612685/49809930-d2cee280-fd68-11e8-8b3b-f20d50237857.png)
