### ISSUE TITLE
Getting ErrImagePull for soluto/tweek-git when running kubernetes

### ISSUE THREAD

**Issue by NadavkOptimalQ** [Soluto/tweek#1120]
Ran:
kubectl apply -f infra/
kubectl apply -f .

Git pod doesn't start due to failing to get the image saying it requires docker-login

Can you check this please?

**Comment by Yshayy** [comment]
The local k8s environment was designed to build with:
https://github.com/Soluto/tweek/blob/master/skaffold.yaml
And there's a mapping from: 
```
image: soluto/tweek-git
context: services/git-service/BareRepository
```

I think replacing "soluto/tweek-git" with "soluto/tweek-bare-repo" in k8s yamls and skaffold.yaml will solve this issue.
