### ISSUE TITLE
How to export tweek rules?

### ISSUE THREAD

**Issue by chirag20388** [Soluto/tweek#1137]
Hi,

I am trying to export tweek rules and to do this I am trying to attach a volume with docker and also looking another way for tweek rest API, but it seems nothing works for me. any hint will be great help for me.

Thanks

**Comment by Yshayy** [comment]
Tweek rules are saved as plain files in a git backend, it's possible to export them by cloning the git service using ssh (git clone ssh://git@localhost:4001/tweek/repo using a private key) or using docker cp to copy /tweek/repo and clone locally. 
It might be also achievable by mounting the /tweek/repo folder.
