### ISSUE TITLE
key folder / name text too long

### ISSUE THREAD

**Issue by gilm31** [Soluto/tweek#117]
![untitled](https://cloud.githubusercontent.com/assets/20421380/21614416/0d3911de-d1e2-11e6-9c7e-839bb01de1f8.png)

standard ui for the case:
wrap the text
show auto "..." at the end, with tooltip on mouse over for full folder name
same for key name

**Comment by nataly87s** [comment]
can be done with css
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
