### ISSUE TITLE
Tweek key linking

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#232]
It would be nice to have the capability of creating a key which is reference for another key.
It can solve a lot of problems related to migration, allow refactoring of our key structures and can provide backward compatibility.

This feature can implemented in both Tweek level or in JPad level.
I think the first iteration should be in Tweek since it's simpler and such capability shouldn't be coupled to the rules engine.

One simple way to achieve it, is applying meta-data on the referencing key with the target key and using management service to duplicate the key definition (format and source) on bundling.

**Comment by Yshayy** [comment]
Maybe we can start by implementing it just on api/management level as Tweek rules loader already support multiple parsers

**Comment by nataly87s** [comment]
related to #274
