### ISSUE TITLE
Context input validation in Tweek API

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#273]
Tweek currently allow to invalid data to context or query configurations with invalid params.
For example:
query with url param device.DeviceOsVersion=unknown (client is getting 500 error)
or posting data to context: 
```
{
     "DeviceOsVersion":"unknown"
}
```
(client get ok response (200) and from that point the context is corrupted, which means calculating keys with matcher that compares the value can result in an error)

Both requests (post to context, get key value/values) should fail with 400 error (bad input) if a context value paramter is mismatched and unconvertable to the context property type definition.

Since the schema is already defined in Tweek, it can easily calculated by the api.

**Comment by Yshayy** [comment]
Since the change in #183, each identity has a single key for schema definition.
The schema's key path is @tweek/schema/{identityType}, value is a JSON object, representing the schema of the identity.

**Comment by omerlh** [comment]
The only question is: Should this be part of the controller? Or a decorator for `IContextDriver` that do input validation? I think the second option is better, as it will affect all operation with the context, and allow code reusing.

**Comment by Yshayy** [comment]
- Decorator might be nicer but we need to make sure it plays nice with the DI, in any case, we need to have a component that manage the lifecycle of schema changes (by listening to rules changed event) https://github.com/Soluto/tweek/blob/master/core/Engine/Engine.Drivers/Rules/IRulesDriver.cs#L9)

- Use ITweek.Calculate and provide "@tweek/schema/_" as path
https://github.com/Soluto/tweek/blob/master/core/Engine/Engine/Api.cs#L92

**Comment by omerlh** [comment]
@Yshayy what should I pass as the last required parameter of this method? the `GetLoadedContextByIdentityType context`? By looking on the usage, it looks pretty complex delegate.

**Comment by omerlh** [comment]
Maybe the mods should be:
* Off
* Report only - only log validation errors
* On
This should make it easier to use - turn it on Report only mode, let it run for a week and look for validation errors.
Pretty similar to HPKP and CSP [report only](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only) mode.

**Comment by Yshayy** [comment]
I think we can add flag for policy:
CONTEXT_VALIDATION_ERROR_POLICY=BYPASS_REPORT

I think "Flexible" will be the best default for most cases.

**Comment by omerlh** [comment]
It might be too complicated to understand what's going on, I think you should only have one flag

**Comment by omerlh** [comment]
What about fixed configuration? e.g. `@fixed:`? currently, I am going to ignore them and always allow them.
