### ISSUE TITLE
security for authoring api

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#502]
#487 
Authoring api will support external clients.
External clients will be defined in git repo under /external_apps/{app_id}.json with a json with the 
following settings:
```
{
     version: 1,
     appName:"",
     secretKeys: [{
         hash:"", //for secret
         salt:"",  //for secret
     }, ...],
     permissions: {
          "keys": {
                "*": ["read", "write"...]
            },
            "schema": {
                 "*": ["read", "write"]
             }
     }
}
````
Current permissions will allow reading, writing keys, in the future we can limit the scope to certain paths.
External Application will use app-id and app-secret to interact with Authoring api.

Requests signed by tweek-editor will have all permissions and an additional actions to add/remove external clients.

@asafkotzer, @nataly87s, @michaelkruglos, @omerlh.

**Comment by omerlh** [comment]
You can take a look on [icinga](https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#authentication) authentication for a reference, it is pretty straight forward.
