### ISSUE TITLE
Add batching support for authoring api service

### ISSUE THREAD

**Issue by DvirSh** [Soluto/tweek#506]
As an addition proposal for [#487](https://github.com/Soluto/tweek/issues/487):

The service API should include an option to batch several keys update as part of one transaction.
I suggest it will be /PUT /keys/batch. It should expect the following payload:
```
[
    {
         "path": "path/to/key",
         "key": #The key content as a string
    }
]
```

**Comment by Yshayy** [comment]
As keys currently use the api of keys/{*}, it would be a problem to use it like this.
I suggest endpoint "bulk-keys-upload" endpoint that get's a zip containing manifests and files

**Comment by DvirSh** [comment]
So, /PUT /bulk-keys-upload that receives a zip file.
