### ISSUE TITLE
Alerts on partial rollout

### ISSUE THREAD

**Issue by omerlh** [Soluto/tweek#536]
Consider the following scenario: I created a key, and used gradual released - let say, 50% true, 50% false. Then, I moved on to the next task and totally forgot about that key. Would be nice to have an email reminder, let's say - after a week - to remind me that I did not complete the rollout.

**Comment by Yshayy** [comment]
I think that once the salt #437 will be up and we'll have datetime operations #165, you can create a rules that increase the rollout automatically by date, something like:
Date> 01/04 -> open to 10%
Date> 04/04 -> open to 30%
Date> 11/04 -> open to 50%
Date> 13/04 -> true

**Comment by Yshayy** [comment]
Closing for now
