### ISSUE TITLE
ContextProvider setting usage in api?

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#585]
While we have the environment variable ContextProvider in api examples, I don't see any code that use it.
Does it means that currently Tweek can't be loaded with two context providers (couchbase and redis)?

**Comment by michaelkruglos** [comment]
You're correct. It's not used anywhere in the code. It was introduced during development, and was left there accidentally.
It does mean that we currently do not support more then one context provider.

**Comment by Yshayy** [comment]
Let's fix it by adding a reflection attribute ContextProviderName and choose the relevant driver based on that setting

**Comment by nataly87s** [comment]
Is this still relevant after the change to that way we load addons in #658 ?

**Comment by Yshayy** [comment]
I think we can close it for now.
