### ISSUE TITLE
Pressing "Enter" when prompted after trying to remove rule will prompt the message again

### ISSUE THREAD

**Issue by nivnahmias** [Soluto/tweek#614]
The re-prompted message will overlay the older message and this can be continued indefinitely.
The "enter" is probably hitting the "X" button on the rule and not the "Ok"/"Cancel" button on the modal.

**Comment by Yshayy** [comment]
Can you write the exact steps to reproduce the bug?

**Comment by Niv1988** [comment]
1. Press "X" to delete rule
2. Press "Enter"
3. Repeat step 2
