### ISSUE TITLE
Source Tab does not render correctly

### ISSUE THREAD

**Issue by nataly87s** [Soluto/tweek#651]
Steps to reproduce:
1. Go to any existing key
2. Switch to the Source tab - it renders correctly
![image](https://user-images.githubusercontent.com/7895237/32562926-8cce9364-c4b8-11e7-9a21-2e68dd0bcca3.png)
3. Switch back to the Rules Tab
4. Switch to the Source tab again - it renders with a height of 5px
![image](https://user-images.githubusercontent.com/7895237/32562878-71b5b832-c4b8-11e7-84f5-f57a11f0f782.png)

**Comment by Yshayy** [comment]
I think it's a regression, maybe related to React upgrade?
