### ISSUE TITLE
Search in editor should be case-insensitive

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#656]
Related to https://github.com/Soluto/tweek-clients/issues/63

### Steps to reproduce:
1. Create a key in Editor
2. Add description Hello
3. Save
4. Wait for search index to refresh
5. Write "Hello" in Editor's search box and make sure you see a result.
6. Write "hello" in search box

### Expected behavior:
We should see our key in the results

### Actual behavior
No results found

**Comment by nataly87s** [comment]
We just need to make the search case insensitive

**Comment by mayashoval** [comment]
yes, like Nataly wrote, please make the search case insensitive :)

**Comment by Yshayy** [comment]
That's pretty much the title of the issue :)
