### ISSUE TITLE
client side JSON validation in tweek editor

### ISSUE THREAD

**Issue by slootzky** [Soluto/tweek#666]
Hey , 
sometimes a text value is actually a JSON.
I think we should consider marking a text key as a JSON and then allow some simple client validation on a new value.
This suggestion is following a real production issue we had because an invalid JSON in one of our keys.

**Comment by Yshayy** [comment]
Hi @slootzky, can you elaborate a bit?
How do we reproduce this problem? Are you talking about manually editing object-type keys?

**Comment by Yshayy** [comment]
Should be solved with #668
