### ISSUE TITLE
Tweek editor not support Object valueType with variants 

### ISSUE THREAD

**Issue by netanelh** [Soluto/tweek#708]
I've created a new key of type 'Object'.
When adding a json as a value to a rule, Tweek will display it as [object object]. However, if I'll try to add a variant to this rule, Tweek will display the values as strings.

**Comment by Yshayy** [comment]
This bug actually goes deeper then the editor, Tweek rules engine currently doesn't support object values in multi-variant keys, I'll open additional issue for that on https://github.com/Soluto/Tweek.JPad
