### ISSUE TITLE
Tweek Policy Management

### ISSUE THREAD

**Issue by AleF83** [Soluto/tweek#837]
Tweek uses [casbin](https://github.com/casbin/casbin) as authorization library.
Each request to one of Tweek services (tweek-api, tweek-authoring) is passed through tweek-gateway and casbin policies are enabled on it.

Each casbin policy has 4 components:
* Subject - who requests to perform the action
* Object - what the action is performed on
* Action - what type of action the subject requests to perform on object
* Effect - allow or deny

So one of the main problems that we encounter is to extract subject, object and action from http request. The data may be stored in jwt claims, url and request body.

So, we need a component that will be responsible for that extraction.

Now, I'll list the cases we need to take care:
Object value is determined by request url.
Action value is determined by http method and request url.
Subject extraction is a bit more problematic.
There are several factors that can affect subject value.
1) JWT claims sub (this is the identifier of the authenticated user)
2) JWT issuer / audience (this value can attest the fact that the user belongs to some group).

So, we need to build the subject value in that format that will contain user identifier and group/role identifier

We use casbin with matcher function that gets sub, obj, act extracted from request and runs over policies (each of them contains sub, obj, act and effect) and invokes the matcher function.
If there is one or more cases that matcher function returns true casbin considers that the request is authorized to perform the action.

I purpose the format extracted from request subject as following:
_\<group\>_:_\<userId\>_
**Group** may be audience or issuer from JWT
Or something fixed for Basic Auth if supported

**UserId** may be sub field from JWT claim or username from Basic Auth.

And the subject in policy definition will be as following:
GroupA:*
GroupB:User1
*:User2

The * symbol means wildcard.

We need extraction mechanism to decide for each case how to construct sub.
It can be something that will check JWT issuer and decide what to get as a group.

**Comment by omerlh** [comment]
Not following - why there is a relation between issuer/audience (which identity provider issue the token) to the group the user belongs to? 

I guess you've considered using IdentityServer to handle this job - create a uniform JWT from all providers with the claims you need, e.g. role. This will allows casbin to decide based on the user role. IdentityServer will be responsible to match the current claims to the user.
