### ISSUE TITLE
Healthcheck should return aggregation of services

### ISSUE THREAD

**Issue by michaelkruglos** [Soluto/tweek#846]
https://github.com/Soluto/tweek/blob/d07262d6107eb32db4fe599101195de4147d293a/services/gateway/transformation/health.go#L16

Add aggregation of api and authoring in output

**Comment by AleF83** [comment]
We have `/version` in `gateway` that returns something like:
```json
// 20180724151626
// http://localhost:4099/version

{
  "api": {
    "version": "0.6.1",
    "status": "healthy"
  },
  "authoring": {
    "version": "0.3.2",
    "status": "healthy"
  },
  "gateway": {
    "version": "0.1.0",
    "status": "healthy"
  },
  "publishing": {
    "version": "0.2.0",
    "status": "healthy"
  }
}
```
Should we set anything more detailed? @Yshayy @michaelkruglos
