### ISSUE TITLE
Running tweek locally fail

### ISSUE THREAD

**Issue by esraajb** [Soluto/tweek#865]
Im trying to run tweek localy for the first time, but it fails to run.

versions:
MacOS High Sierra 10.13.3
Node v10.7.0
Docker v18.03.1-ce, build 9ee9f40
docker-compose v1.21.1, build 5a3f1a3

What I did:
1) cloned the repo
2) cd to tweek
3) yarn start

<img width="1451" alt="screen shot 2018-07-31 at 7 30 29 am" src="https://user-images.githubusercontent.com/21229375/43437843-bb7cf754-9493-11e8-881e-1a1ea6c6fb17.png">

If I remove "**/*" from .dockerignore file, it pass the previous step but fails in a later one: 
<img width="1442" alt="screen shot 2018-07-31 at 7 35 11 am" src="https://user-images.githubusercontent.com/21229375/43437955-62c7f8ce-9494-11e8-8ebe-3b5e4296ba73.png">

**Comment by Yshayy** [comment]
Hi, 
can you try using latest Docker Compose?
https://github.com/docker/compose/releases (1.22.0)

Thanks

**Comment by esraajb** [comment]
Tried with dc1.22 and  d18.06, still same problem.

Ill look into the issues later.

**Comment by esraajb** [comment]
Worked on the second try with 1.22 and 18.06. 
Thanks.
