### ISSUE TITLE
Archived keys can be chosen to be a dependent key.

### ISSUE THREAD

**Issue by tal952** [Soluto/tweek#992]
Archived keys can be chosen to be a dependent key.

![image](https://user-images.githubusercontent.com/1283559/48561520-d2bdfd00-e8f8-11e8-89df-34fcdc12a6c7.png)

**Comment by Yshayy** [comment]
Is there a problem that archived key is a dependency? There might be some cases when dealing with legacy keys that this behavior is desired.

**Comment by tal952** [comment]
There is no really a problem with an archived key is a dependency, but it doesn't make sense to suggest it. For example, if I created a key named "is_enabled", archive it and created a key named "enabled", I think it's not making sense to show both as suggestions, it can lead to confusion.

We can allow to put an archived key for special cases, but just not suggest it as an option.
